---
title: "Morning Letter"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: fill
---
  
  
```{r setup, include=FALSE}

rm(list=ls())

library(flexdashboard)
library(RSelenium)
library(XML)
library(rvest)
library(stringr)
library(knitr)
library(dplyr)
library(tidyr)
library(lubridate)
library(httr)
library(readxl)
library(writexl)
library(jsonlite)
library(kableExtra)
library(DT)


rD <- rsDriver(port=4775L, chromever="100.0.4896.60")
remDr <- rD$client


## 날짜 및 시간 설정
now <- Sys.time()
today <- format(Sys.time(), "%Y.%m.%d.")

## 팟빵 에피소드 수집 함수 선언
podbbang <- function(channel.id) {
  
  URL <- str_c("http://www.podbbang.com/_m_api/podcasts/", channel.id, "/episodes?offset=0&sort=pubdate:desc&episode_id=0&limit=8&with=summary&cache=0")
  
  txt <- readLines(URL, warn=FALSE)
  
  df <- fromJSON(txt)$data %>% 
    select(published_at, title, duration)
  
  names(df) <- c("date", "title", "duration")
  
  df$date <- df$date %>% 
    as.Date() %>% 
    format("%y.%m.%d")
  
  df$title <- df$title %>% 
    str_remove_all("^[0-9]{2}/[0-9]{2} -") %>% 
    str_trim()
  
  return(df)
  
}


## Naver News Keyword Search
naver.news.api.search <-function(keyword) {
  
searchUrl <- "https://openapi.naver.com/v1/search/news.xml"
client_id <- "M4g9rW2aSU0zNVXbp0Ve"
client_secret <- "gfr6xh20HF"

search.word <- keyword
query <- search.word %>% 
  enc2utf8() %>% 
  URLencode()

url <- str_c(searchUrl, "?query=", query, "&display=20")

res <- GET(url, 
           add_headers("X-Naver-Client-Id"=client_id, 
                       "X-Naver-Client-Secret"=client_secret))
doc <- toString(res)

xmlFile <- xmlParse(doc)
xmlRoot(xmlFile)
df <- xmlToDataFrame(getNodeSet(xmlFile, "//item"), stringsAsFactors = FALSE)
  
}

```



1. News
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------
### Chart A1 (**Issued at `r now`**)

**네이버 뉴스 검색**

```{r}
list <- c("마부작침", "한국사회과학자료원")
Stack <- NULL
for (keyword in list) {
  
  query <- keyword
  tab <- naver.news.api.search(query)
  tab <- cbind(query, tab) 
  tab <- tab %>% select(-originallink, -description)
  tab <- tab %>% 
    mutate(pubDate = str_remove(pubDate, " \\d{2}:.+")) %>% 
    mutate(title = str_replace_all(title, "&quot;", '"'))

  Stack <- rbind(Stack, tab) 
  
}

names(Stack) <- c("Search", "Title", "Link", "Date")

df <- Stack %>%
  mutate(Title = cell_spec(Title, "html", link = Link, color="#062872")) %>% 
  select(Date, Search, Title)

df %>% 
  kable(escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "10em") %>%
  column_spec(3, width = "30em")
```


### Chart A2

**네이버 뉴스 검색**

```{r}
list <- c("불평등", "사교육")
Stack <- NULL
for (keyword in list) {
  
  query <- keyword
  tab <- naver.news.api.search(query)
  tab <- cbind(query, tab) 
  tab <- tab %>% select(-originallink, -description)
  tab <- tab %>% 
    mutate(pubDate = str_remove(pubDate, " \\d{2}:.+")) %>% 
    mutate(title = str_replace_all(title, "&quot;", '"'))

  Stack <- rbind(Stack, tab) 
  
}

names(Stack) <- c("Search", "Title", "Link", "Date")

df <- Stack %>%
  mutate(Title = cell_spec(Title, "html", link = Link, color="#062872")) %>% 
  select(Date, Search, Title)

df %>% 
  kable(escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "10em") %>%
  column_spec(2, width = "10em") %>%
  column_spec(3, width = "30em")
```





Column {data-width=500}
-----------------------------------------------------------------------

### Chart B1

[Youtube: Arirang News](https://www.youtube.com/c/ArirangCoKrArirangNEWS)

```{r, include=FALSE}
URL <- "https://www.youtube.com/c/ArirangCoKrArirangNEWS/videos"

remDr$navigate(URL)

Sys.sleep(3)
# remDr %>% setTimeout(type = "page load", milliseconds = 10000)

txt <- remDr$getPageSource()[[1]]

res <- read_html(txt)

title <- res %>%
  html_nodes("#video-title") %>%
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

link <- res %>%
  html_nodes("#video-title") %>%
  html_attr("href") %>%
  str_c("https://www.youtube.com", .)

date <- res %>%
  html_nodes("#metadata-line > span:nth-child(2)") %>%
  html_text() %>% 
  str_remove("스트리밍 시간: ")

length <- res %>%
  html_nodes("#overlays > ytd-thumbnail-overlay-time-status-renderer > span") %>%
  html_text() 

tbl <- cbind(date, title, length, link) %>%
  as.data.frame(stringsAsFactors=FALSE)

df <- tbl %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(date, title.link, length)

names(df) <- c("Date", "Title", "Length")
```

```{r}
df %>% head(15) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "35em") %>%
  column_spec(3, width = "6em")
```



### Chart B2

[Youtube: 유 퀴즈 온 더 튜브](https://www.youtube.com/channel/UC920m3pMPH45qztdhppZhwA)

```{r, include=FALSE}
URL <- "https://www.youtube.com/channel/UC920m3pMPH45qztdhppZhwA/videos"

remDr$navigate(URL)

Sys.sleep(3)
# remDr %>% setTimeout(type = "page load", milliseconds = 10000)

txt <- remDr$getPageSource()[[1]]

res <- read_html(txt)

title <- res %>%
  html_nodes("#video-title") %>%
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

link <- res %>%
  html_nodes("#video-title") %>%
  html_attr("href") %>%
  str_c("https://www.youtube.com", .)

date <- res %>%
  html_nodes("#metadata-line > span:nth-child(2)") %>%
  html_text() %>% 
  str_remove("스트리밍 시간: ")

length <- res %>%
  html_nodes("#overlays > ytd-thumbnail-overlay-time-status-renderer > span") %>%
  html_text() 

tbl <- cbind(date, title, length, link) %>%
  as.data.frame(stringsAsFactors=FALSE)

df <- tbl %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(date, title.link, length)

names(df) <- c("Date", "Title", "Length")
```

```{r}
df %>% head(15) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "35em") %>%
  column_spec(3, width = "6em")

Sys.sleep(1)
```





2. Podcast
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------
### Chart A1 (**Issued at `r now`**)

[이진우의 손에 잡히는 경제](http://www.podbbang.com/ch/75), [Youtube MBC라디오](https://www.youtube.com/channel/UCTTmtS2ljy1vyl_s-d_LEHQ/playlists)

```{r}
channel.name <- "이진우의 손에 잡히는 경제"
channel.id <- 75

df<-podbbang(channel.id)
df %>% head(10) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "35em") %>%
  column_spec(3, width = "6em")
```




### Chart A2

[데이터홀릭](http://www.podbbang.com/ch/1771386)

```{r}
channel.name <- "데이터홀릭"
channel.id <- 1771386

df<-podbbang(channel.id)
df %>% head(10) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "35em") %>%
  column_spec(3, width = "6em")
```




Column {data-width=500}
-----------------------------------------------------------------------

### Chart B1

[김종배의 시선집중](http://www.podbbang.com/ch/61), [Youtube MBC라디오](https://www.youtube.com/channel/UCTTmtS2ljy1vyl_s-d_LEHQ/playlists)

```{r}
channel.name <- "김종배의 시선집중"
channel.id <- 61

df<-podbbang(channel.id)
df %>% head(10) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "35em") %>%
  column_spec(3, width = "6em")
```



### Chart B2

[세바시](http://www.podbbang.com/ch/222)

```{r}
channel.name <- "세바시"
channel.id <- 222

df<-podbbang(channel.id)
df %>% head(10) %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed")) %>%
  column_spec(1, width = "6em") %>%
  column_spec(2, width = "35em") %>%
  column_spec(3, width = "6em")
```



```{r, include=FALSE}
remDr$close()
rD$server$stop()
system("taskkill /im java.exe /F")
```