---
title: "경제데이터분석입문 Final_Yoo in Cheol"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rvest)
library(dplyr)
library(stringr)
library(knitr)
library(kableExtra)
library(RSelenium)

rD <- rsDriver(port=4980L, "firefox")
remDr <- rD$client

## 날짜 및 시간 설정
now <- Sys.time()
today <- format(Sys.time(), "%Y.%m.%d.")
```

M&A 주요기사 [아침] {data-icon="fa-list"} 
===================================== 

Column {data-width=500}
-----------------------------------------------------------------------
<< PEF 사설>>

### PEF 썰전 (**`r now`**) [Link](https://www.hankyung.com/tag/PEF%EC%8D%B0%EC%A0%84?page=1)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")

Stack <- NULL


URL <- "https://www.hankyung.com/tag/PEF%EC%8D%B0%EC%A0%84?page=1"
  
res <- read_html(URL)
pattern <- ".txt a"
title <- res %>%
  html_nodes(pattern) %>%
  html_text()
  
  pattern <- ".time"
  date <- res %>%
    html_nodes(pattern) %>%
    html_text()
  
  pub.date <- str_sub(date, 1, 10)
  
  pattern <-"#container > div.contents_wrap > div.contents > div.news_list_wrap > ul > li > div.txt > h3 > a"
  
  link <- res %>%
    html_nodes(pattern) %>%
    html_attr("href")
  
  tab <- cbind(pub.date, title, link) %>% as_tibble()
  
  Stack <- rbind(Stack, tab)
  

 

df <- Stack %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(pub.date, title.link)

names(df) <- c("Date", "Headline")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

### 한경 CFO Insight (**`r now`**) [Link](https://page.stibee.com/archives/83403)

```{r}
date.search <- format(Sys.time(), "%Y%m%d")

URL <- "https://page.stibee.com/archives/83403"
remDr$navigate(URL)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)

frames = remDr$findElements(using = "id", value = "root")

pattern <- ".title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_trim()

pattern <- ".date"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_trim()

pub.date <- str_sub(date, 1, 10) %>% str_trim()

pattern <- "#stb_archives > div.stb_archives_body > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href")



tab <- cbind(pub.date, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(pub.date, title.link)

names(df) <- c("Date", "Headline")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))


```

### PEF 밸류업 사례탐구 (**`r now`**) [Link](https://www.hankyung.com/tag/PEF-%EB%B0%B8%EB%A5%98%EC%97%85-%EC%82%AC%EB%A1%80%ED%83%90%EA%B5%AC)

```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.hankyung.com/tag/PEF-%EB%B0%B8%EB%A5%98%EC%97%85-%EC%82%AC%EB%A1%80%ED%83%90%EA%B5%AC"

res <- read_html(URL)
pattern <- ".txt a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- ".time"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pub.date <- str_sub(date, 1, 10)

pattern <- "#container > div.contents_wrap > div.contents > div.news_list_wrap > ul > li > div.txt > h3 > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href")

tab <- cbind(pub.date, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(pub.date, title.link)

names(df) <- c("Date", "Headline")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


Column {data-width=500}
-----------------------------------------------------------------------
<< M&A 주요 뉴스 >>

### 마켓인사이트 (**`r now`**) [Link](https://marketinsight.hankyung.com/freenews?page=1)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")

Stack <- NULL

for(i in 1:5){
  URL <- str_c("https://marketinsight.hankyung.com/freenews?page=", i)
  
  res <- read_html(URL)
  pattern <- ".news-tit a"
  title <- res %>%
    html_nodes(pattern) %>%
    html_text()
  
  pattern <-
    "#contents > div > div > div.cont-free > ul > li > div.txt-cont > h3 > a"
  
  date <- res %>%
    html_nodes(pattern) %>%
    html_attr("href")
  
  pub.date <-
    str_c(str_sub(date, 38, 41),
          ".",
          str_sub(date, 42, 43),
          ".",
          str_sub(date, 44, 45))
  
  
  pattern <- "#contents > div > div > div.cont-free > ul > li > div.txt-cont > h3 > a"
  
  link <- res %>%
    html_nodes(pattern) %>%
    html_attr("href") %>%
    str_c("https:", .)
  
  
  tab <- cbind(pub.date, title, link) %>% as_tibble()  
  
  Stack <- rbind(Stack, tab)
  
  Sys.sleep(1)
  
}


df <- Stack %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(pub.date, title.link)

names(df) <- c("Date", "Headline")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


-----------------------------------------------------------------------

### The Bell (더벨) (**`r now`**) [Link](https://www.thebell.co.kr/free/content/article.asp?svccode=01)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.thebell.co.kr/free/content/article.asp?svccode=01"

res <- read_html(URL)
pattern <- ".listBox dt"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- ".date"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pub.date <- str_c(str_sub(date, 1, 4), ".", str_sub(date, 6, 7), ".", str_sub(date, 9, 10))

pattern <- "#contents > div.contentSection > div > div.newsBox > div.newsList > div.listBox > ul > li > dl > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.thebell.co.kr/free/content/", .)

tab <- cbind(pub.date, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(pub.date, title.link)

names(df) <- c("Date", "Headline")

df %>% head(10) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

### 인베스트조선 (**`r now`**) [Link](https://www.investchosun.com/svc/news/list.html?catid=2)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.investchosun.com/svc/news/list.html?catid=2"

res <- read_html(URL)
pattern <- "dt a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- ".date span:nth-child(1)"
pub.date <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- "body > div > div > ul > li > div > dl > dd.summary > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.investchosun.com/", .)

tab <- cbind(pub.date, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(pub.date, title.link)

names(df) <- c("Date", "Headline")

df %>% head(15) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

여의도 맛집 [점심] {data-icon="fa-hashtag"}
=====================================

Row {data-height=300}
-------------------------------------

### 한식 (**`r now`**) [Link](https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%ED%95%9C%EC%8B%9D)
    
```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%ED%95%9C%EC%8B%9D"


res <- read_html(URL)

pattern <- ".restaurant-item .title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > strong"
star <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- ".etc span"
menu <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div> figure > figcaption > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.mangoplate.com/", .)

tab <- cbind(star, title, link, menu) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(star, title.link, menu)

names(df) <- c("Star", "Headline", "Menu")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

### 세계음식 (**`r now`**) [Link](https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%84%B8%EA%B3%84%EC%9D%8C%EC%8B%9D)
```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%84%B8%EA%B3%84%EC%9D%8C%EC%8B%9D"


res <- read_html(URL)

pattern <- ".restaurant-item .title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

pattern <- ".etc span"
menu <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > strong"
star <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 


pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div> figure > figcaption > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.mangoplate.com/", .)

tab <- cbind(star, title, link, menu) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(star, title.link, menu)

names(df) <- c("Star", "Headline", "Menu")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

Row {data-height=300}
-------------------------------------
### 일식 (**`r now`**) [Link](https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84%20%EC%9D%BC%EC%8B%9D)
    
```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84%20%EC%9D%BC%EC%8B%9D"


res <- read_html(URL)

pattern <- ".restaurant-item .title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > strong"
star <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- ".etc span"
menu <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div> figure > figcaption > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.mangoplate.com/", .)

tab <- cbind(star, title, link, menu) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(star, title.link, menu)

names(df) <- c("Star", "Headline", "Menu")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

### 양식 (**`r now`**) [Link](https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%96%91%EC%8B%9D)
    
```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%96%91%EC%8B%9D"


res <- read_html(URL)

pattern <- ".restaurant-item .title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > p.etc"
menu <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("여의도") %>% 
  str_remove("-") %>% 
  str_trim()

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > strong"
star <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 


pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div> figure > figcaption > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.mangoplate.com/", .)

tab <- cbind(star, title, link, menu) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(star, title.link, menu)

names(df) <- c("Star", "Headline", "Menu")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```


    

Row {data-height=300}
-------------------------------------

### IFC (**`r now`**) [Link](https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84%20ifc")
    
```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84%20ifc"


res <- read_html(URL)

pattern <- ".restaurant-item .title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

pattern <- ".etc span"
menu <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > strong"
star <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 


pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div> figure > figcaption > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.mangoplate.com/", .)

tab <- cbind(star, title, link, menu) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(star, title.link, menu)

names(df) <- c("Star", "Headline", "Menu")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

### 카페 (**`r now`**) [Link](https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%B9%B4%ED%8E%98)
    
```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%B9%B4%ED%8E%98"


res <- read_html(URL)

pattern <- ".restaurant-item .title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > strong"
star <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- ".etc span"
menu <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div> figure > figcaption > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.mangoplate.com/", .)

tab <- cbind(star, title, link, menu) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(star, title.link, menu)

names(df) <- c("Star", "Headline", "Menu")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

### 술집 (**`r now`**) [Link](https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%88%A0%EC%A7%91)
    
```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mangoplate.com/search/%EC%97%AC%EC%9D%98%EB%8F%84-%EC%88%A0%EC%A7%91"


res <- read_html(URL)

pattern <- ".restaurant-item .title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_remove("\n") %>% 
  str_trim()

pattern <- ".etc span"
menu <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 


pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div > figure > figcaption > div > strong"
star <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 


pattern <- "body > main > article > div.column-wrapper > div > div > section > div.search-list-restaurants-inner-wrap > ul > li > div> figure > figcaption > div > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.mangoplate.com/", .)

tab <- cbind(star, title, link, menu) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(star, title.link, menu)

names(df) <- c("Star", "Headline", "Menu")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```


퇴근후의 삶 [저녁] {data-icon="fa-list"} 
=====================================

Row {data-height=500}
-------------------------------------
<< 채용공고 >>

### 일반기업 (**`r now`**) [Link](https://www.kicpa.or.kr/home/jobOffrSrchGnrl/list.face?ijJobSep=1&ijCoSep=4&listCnt=150&FsrhTab=4)
    
```{r}
date.search <- format(Sys.time(), "%Y%m%d")

URL <- "https://www.kicpa.or.kr/home/jobOffrSrchGnrl/list.face?ijJobSep=1&ijCoSep=4&listCnt=150&FsrhTab=4"
remDr$navigate(URL)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)

frames = remDr$findElements(using = "id", value = "IframePortlet_8978")

pattern <- "#sub_contents > div.sec.sec_01.on > div:nth-child(1) > table > tbody > tr > td.subject > a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_trim()

pattern <- "#sub_contents > div.sec.sec_01.on > div:nth-child(1) > table > tbody > tr > td:nth-child(6)"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>% 
  str_trim()

pub.date <- str_sub(date, 1, 10) %>% str_trim()

pattern <- "#sub_contents > div.sec.sec_01.on > div:nth-child(1) > table > tbody > tr > td.subject > a"
link <- "https://www.kicpa.or.kr/home/jobOffrSrchGnrl/list.face?ijJobSep=1&ijCoSep=4&listCnt=150&FsrhTab=4"

tab <- cbind(pub.date, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(pub.date, title.link)

names(df) <- c("공고일", "채용공고")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

### 삼일회계법인 (**`r now`**) [Link](https://www.pwc.com/kr/ko/career/experienced.html)

```{r}

URL <- "https://www.pwc.com/kr/ko/career/experienced.html"

res <- read_html(URL)

pattern <- "td:nth-child(1) a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- "tr+ tr td:nth-child(2)"
service <- res %>% 
  html_nodes(pattern) %>% 
  html_text() 

pattern <- "#content-free-1-920b > div > div.table.text.parbase.striped.section > div > table > tbody > tr > td:nth-child(1) > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.pwc.com",.)

tab <- cbind(service, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(service, title.link)

names(df) <- c("Service", "Job title")

df %>% head(20) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

    
Row {data-height=500} 
-------------------------------------
<<휴식 시간>>

### 넷플릭스 한국드라마(**Issued at `r now`**) [Link](https://www.netflix.com/kr)

```{r}

URL <- "https://www.netflix.com/kr/browse/genre/2638104"

res <- read_html(URL)
pattern <- ".nm-collections-title-name"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()



source <- "NETFLEX"


pattern <- "#appMountPoint > div > div.nm-collections-page > main > section:nth-child(2) > div > ul > li > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href")

tab <- cbind(source, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(source, title.link)

names(df) <- c("Source", "Headline")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

### 케이시(Kassy) (**`r now`**) [Link](https://www.vlive.tv/channel/E2539B)

```{r}

URL <- "https://www.vlive.tv/channel/E2539B/board/4376"
remDr$navigate(URL)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)

frames = remDr$findElements(using = "id", value = "IframePortlet_8978")

pattern <- "#root > div > div.layout_main--2iozc > div.layout_content--3-hGQ > div.board_container--jTnd3 > ul > li > a > div > div.content_area--24ZuP > div.post_title--3sJDT > strong"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

Sys.sleep(3)

pattern <- ".upload_time--wtBj9"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text()


pattern <- "#root > div > div.layout_main--2iozc > div.layout_content--3-hGQ > div.board_container--jTnd3 > ul > li > a"
link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.vlive.tv", .)

tab <- cbind(date, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(date, title.link)

names(df) <- c("Date", "Headline")

df %>% head(length(title)) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

system("taskkill /im java.exe /F")

```
