---
title: "경제데이터분석입문 Final_Yoo in Cheol"
output: 
  flexdashboard::flex_dashboard:
  orientation: columns
vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(rvest)
library(dplyr)
library(stringr)
library(knitr)
library(kableExtra)
library(RSelenium)


## 날짜 및 시간 설정
now <- Sys.time()
today <- format(Sys.time(), "%Y.%m.%d.")
```

M&A 주요기사 {data-icon="fa-list"} 
===================================== 

Column {data-width=500}
-----------------------------------------------------------------------
### 마켓인사이트 (**Issued at `r now`**)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://marketinsight.hankyung.com/freenews"

res <- read_html(URL)
pattern <- ".news-tit a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- "#contents > div > div > div.cont-free > ul > li:nth-child(1) > div.txt-cont > h3 > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https:", .)


tab <- cbind(today, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(today, title.link)

names(df) <- c("Date", "Headline")

df %>% head(15) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


-----------------------------------------------------------------------

### The Bell (더벨) (**Issued at `r now`**)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.thebell.co.kr/free/content/article.asp?svccode=01"

res <- read_html(URL)
pattern <- ".listBox dt"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- "#contents > div.contentSection > div > div.newsBox > div.newsList > div.listBox > ul > li > dl > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.thebell.co.kr/free/content/", .)

tab <- cbind(today, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(today, title.link)

names(df) <- c("Date", "Headline")

df %>% head(10) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


### 인베스트조선 (**Issued at `r now`**)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.investchosun.com/svc/news/list.html?catid=2"

res <- read_html(URL)
pattern <- "dt a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- "body > div > div > ul > li > div > dl > dd.summary > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://www.investchosun.com/", .)

tab <- cbind(today, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(today, title.link)

names(df) <- c("Date", "Headline")

df %>% head(15) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


Column {data-width=500}
-----------------------------------------------------------------------

### 매일경제 M&A (**Issued at `r now`**)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://www.mk.co.kr/news/list_kword.php?kword=M%26A"

res <- read_html(URL)
pattern <- "#container_left .tit a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- "#container_left > dl > dt > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href")

tab <- cbind(today, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(today, title.link)

names(df) <- c("Date", "Headline")

df %>% head(20) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```


### 팍스넷 PEF (**Issued at `r now`**)

```{r}
# date.search <- "20210811"
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://paxnetnews.com/categories/075033"

res <- read_html(URL)
pattern <- ".ss-news-top-title"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- "body > div.contents.small-top > div > div.content-main > div.mnm-news-list > div> div > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href") %>% 
  str_c("https://paxnetnews.com", .)

tab <- cbind(today, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(today, title.link)

names(df) <- c("Date", "Headline")

df %>% head(20) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
```

IR 자료{data-icon="fa-hashtag"}
=====================================

Row {data-height=500}
-------------------------------------

### 한국거래소 IR (**Issued at `r now`**)

```{r}
date.search <- format(Sys.time(), "%Y%m%d")
URL <- "https://kind.krx.co.kr/corpgeneral/irschedule.do?method=searchIRScheduleMain&gubun=iRMaterials"

res <- read_html(URL)
pattern <- "#main-contents .vmiddle+ a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

res <- read_html(URL)
pattern <- ".first.txc"
number <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

res <- read_html(URL)
pattern <- ".txc:nth-child(3)"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text()

pattern <- "#main-contents > section.scrarea.type-00 > table > tbody > tr.first > td > a"

link <- res %>% 
  html_nodes(pattern) %>% 
  html_attr("href")

tab <- cbind(today, title, link) %>% as_tibble()

df <- tab %>%
  mutate(title.link = cell_spec(title, "html", link = link, color="#062872")) %>%
  select(today, title.link)

names(df) <- c("Date", "Headline")

df %>% head(20) %>%
  kable(format="html", escape=FALSE) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"))

```

### 코스닥협회 IR (**Issued at `r now`**)
    
```{r}
```
    
Row {data-height=500}
-------------------------------------
    
### Dart 공시 (**Issued at `r now`**)

```{r}
```
